language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "ricm5-ecom-groupe5-2017-2018"
    token:
      secure: "e98d2f1c4038566bc3a06969dbf0b05100a55965"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'