package model;
// Generated 11 nov. 2017 18:56:02 by Hibernate Tools 5.1.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Agency generated by hbm2java
 */
@Entity
@Table(name = "agency", catalog = "Mes_Transports")
public class Agency implements java.io.Serializable {

	private Integer id;
	private String type;
	private String address;
	private Integer idMotherAgency;
	private String phoneNum;
	private String city;
	private String name;
	private String bankLink;
	private String bankName;
	private String rib;

	public Agency() {
	}

	public Agency(String type, String address, String phoneNum) {
		this.type = type;
		this.address = address;
		this.phoneNum = phoneNum;
	}

	public Agency(String type, String address, Integer idMotherAgency, String phoneNum) {
		this.type = type;
		this.address = address;
		this.idMotherAgency = idMotherAgency;
		this.phoneNum = phoneNum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false, length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "id_mother_agency")
	public Integer getIdMotherAgency() {
		return this.idMotherAgency;
	}

	public void setIdMotherAgency(Integer idMotherAgency) {
		this.idMotherAgency = idMotherAgency;
	}

	@Column(name = "phone_num", nullable = false, length = 65535)
	public String getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getBankLink() {
		return bankLink;
	}

	public void setBankLink(String bankLink) {
		this.bankLink = bankLink;
	}

	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getRib() {
		return rib;
	}

	public void setRib(String rib) {
		this.rib = rib;
	}
}
