package model;

// default package
// Generated 24 oct. 2017 17:46:56 by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AssignCharacteristic generated by hbm2java
 */
@Entity
@Table(name = "ASSIGN_CHARACTERISTIC", catalog = "test")
public class AssignCharacteristic implements java.io.Serializable {

	private AssignCharacteristicId id;
	private String valueCharacteristic;

	public AssignCharacteristic() {
	}

	public AssignCharacteristic(AssignCharacteristicId id, String valueCharacteristic) {
		this.id = id;
		this.valueCharacteristic = valueCharacteristic;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idVehicle", column = @Column(name = "idVehicle", nullable = false)),
			@AttributeOverride(name = "idCharacteristic", column = @Column(name = "idCharacteristic", nullable = false)) })
	public AssignCharacteristicId getId() {
		return this.id;
	}

	public void setId(AssignCharacteristicId id) {
		this.id = id;
	}

	@Column(name = "valueCharacteristic", nullable = false)
	public String getValueCharacteristic() {
		return this.valueCharacteristic;
	}

	public void setValueCharacteristic(String valueCharacteristic) {
		this.valueCharacteristic = valueCharacteristic;
	}

}
