package model;
// Generated 11 nov. 2017 18:56:02 by Hibernate Tools 5.1.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * AssignCharacteristicId generated by hbm2java
 */
@Embeddable
public class AssignCharacteristicId implements java.io.Serializable {

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="idVehicle")
	private int idVehicle;
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="idCharacteristic")
	private int idCharacteristic;

	public AssignCharacteristicId() {
	}

	public AssignCharacteristicId(int idVehicle, int idCharacteristic) {
		this.idVehicle = idVehicle;
		this.idCharacteristic = idCharacteristic;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="idVehicle", nullable = false)
	public int getIdVehicle() {
		return this.idVehicle;
	}

	public void setIdVehicle(int idVehicle) {
		this.idVehicle = idVehicle;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="idCharacteristic")
	@Column(name = "idCharacteristic", nullable = false)
	public int getIdCharacteristic() {
		return this.idCharacteristic;
	}

	public void setIdCharacteristic(int idCharacteristic) {
		this.idCharacteristic = idCharacteristic;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AssignCharacteristicId))
			return false;
		AssignCharacteristicId castOther = (AssignCharacteristicId) other;

		return (this.getIdVehicle() == castOther.getIdVehicle())
				&& (this.getIdCharacteristic() == castOther.getIdCharacteristic());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdVehicle();
		result = 37 * result + this.getIdCharacteristic();
		return result;
	}

}
