package model;

// default package
// Generated 24 oct. 2017 17:46:56 by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AssignCharacteristicId generated by hbm2java
 */
@Embeddable
public class AssignCharacteristicId implements java.io.Serializable {

	private int idVehicle;
	private int idCharacteristic;

	public AssignCharacteristicId() {
	}

	public AssignCharacteristicId(int idVehicle, int idCharacteristic) {
		this.idVehicle = idVehicle;
		this.idCharacteristic = idCharacteristic;
	}

	@Column(name = "idVehicle", nullable = false)
	public int getIdVehicle() {
		return this.idVehicle;
	}

	public void setIdVehicle(int idVehicle) {
		this.idVehicle = idVehicle;
	}

	@Column(name = "idCharacteristic", nullable = false)
	public int getIdCharacteristic() {
		return this.idCharacteristic;
	}

	public void setIdCharacteristic(int idCharacteristic) {
		this.idCharacteristic = idCharacteristic;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AssignCharacteristicId))
			return false;
		AssignCharacteristicId castOther = (AssignCharacteristicId) other;

		return (this.getIdVehicle() == castOther.getIdVehicle())
				&& (this.getIdCharacteristic() == castOther.getIdCharacteristic());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdVehicle();
		result = 37 * result + this.getIdCharacteristic();
		return result;
	}

}
