package model;

// default package
// Generated 24 oct. 2017 17:46:56 by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CharacteristicTypeId generated by hbm2java
 */
@Embeddable
public class CharacteristicTypeId implements java.io.Serializable {

	private int idType;
	private int idCharacteristic;

	public CharacteristicTypeId() {
	}

	public CharacteristicTypeId(int idType, int idCharacteristic) {
		this.idType = idType;
		this.idCharacteristic = idCharacteristic;
	}

	@Column(name = "idType", nullable = false)
	public int getIdType() {
		return this.idType;
	}

	public void setIdType(int idType) {
		this.idType = idType;
	}

	@Column(name = "idCharacteristic", nullable = false)
	public int getIdCharacteristic() {
		return this.idCharacteristic;
	}

	public void setIdCharacteristic(int idCharacteristic) {
		this.idCharacteristic = idCharacteristic;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CharacteristicTypeId))
			return false;
		CharacteristicTypeId castOther = (CharacteristicTypeId) other;

		return (this.getIdType() == castOther.getIdType())
				&& (this.getIdCharacteristic() == castOther.getIdCharacteristic());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdType();
		result = 37 * result + this.getIdCharacteristic();
		return result;
	}

}
