package model;
// Generated 11 nov. 2017 18:56:02 by Hibernate Tools 5.1.5.Final

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;


/**
 * Characteristic generated by hbm2java
 */
@Entity
@Table(name = "characteristic", catalog = "Mes_Transports")
public class Characteristic implements java.io.Serializable {

	private Integer id;
	private String unit;
	private String label;
	
	@JsonIgnore
    private List<AssignCharacteristic> characteristicList = new ArrayList<AssignCharacteristic>();

	@Column(name="rank", unique = true)
	private Integer rank;

	private boolean optional;

	public Characteristic() {
	}

	public Characteristic(String unit, String label, boolean optional) {
		this.unit = unit;
		this.label = label;
		this.optional = optional;
	}

	public Integer getRank() {
		return this.rank;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "unit", nullable = false, length = 100)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "label", nullable = false, length = 100)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "optional", nullable = false)
	public boolean isOptional() {
		return this.optional;
	}

	public void setOptional(boolean optional) {
		this.optional = optional;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}
	
	@OneToMany(fetch = FetchType.EAGER,mappedBy = "characteristic")
	@JsonIgnore
	public List<AssignCharacteristic> getCharacteristicList() {
		return characteristicList;
	}

	public void setCharacteristicList(List<AssignCharacteristic> characteristicList) {
		this.characteristicList = characteristicList;
	}
	
	
}
